//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Data;
using AppCount.Classes;
namespace AppCount.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProyectoActivo 
        {
            get {
                return ((string)(this["ProyectoActivo"]));
            }
            set {
                this["ProyectoActivo"] = value;
            }
        }

        public AppCount.Classes.Proyectos Proyecto
        {
            get;
            set;
        }
        public ArrayList CuentasAL
        {
            get
            {
                FileManager fm = new FileManager("Cuentas.bin");
                return (ArrayList)fm.readObject();
            }
        }
        public DataTable CuentasDT
        {
            get
            {
                DataTable cuentas = new DataTable();
                cuentas.Columns.Add("CuentaPK", System.Type.GetType("System.Decimal"));
                cuentas.Columns.Add("Cuenta", System.Type.GetType("System.String"));
                foreach (Classes.Cuentas cuenta in AppCount.Properties.Settings.Default.CuentasAL)
                    cuentas.Rows.Add(new object[] { cuenta.CuentaPK, cuenta.ToString() });

                return cuentas;
            }
        }
        public Hashtable CuentasHT { get; set; }
    }
}
